[package]
name = "uc_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
uc_name = { path = "../uc_name" }
uc_files = { path = "../uc_files" }
