[workspace]
members = [
    "uc_analysis",
    "uc_analyzer",
    "uc_ast",
    "uc_ast_lowering",
    "uc_def",
    "uc_files",
    "uc_middle",
    "uc_name",
    "uc_parser",
]

[profile.dev]
opt-level = 1
