[package]
name = "uc_middle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uc_def = { path = "../uc_def" }
uc_name = { path = "../uc_name" }
uc_types = { path = "../uc_types" }
